name: FTPS Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.electronicsweekly.ir.com
          username: info@electronicsweekly.ir.com
          password: ${{ secrets.ftp_password }}
          protocol: ftps
